spec:
  replicas: 1
  template:
    spec:
      containers:
        - env:
          - name: WILDFLY_METRICS_URL
            valueFrom:
              configMapKeyRef:
                name: wildfly-settings
                key: wildfly.metrics.url
