version: "3"

services:
  idp:
    hostname: idp
    image: auth-test/app-jee-html5-keycloak:0.3.0
    volumes:
      - ".:/tmp/output"
    networks:
      app-jee-html5:
        aliases:
          - idp
    ports:
      - "8081:8080"
    environment:
      - WEB_URL=http://${THIS_HOST:?err}:8080/app-html5
      - LDAP_URL=N/A
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin

  web:
    hostname: web
    image: auth-test/app-jee-html5-wildfly:0.3.0
    networks:
      app-jee-html5:
        aliases:
          - web
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    environment:
      - JCMS_JBOSS_SERVER_OPTS=--debug 8787
      - IDP_URL=http://${THIS_HOST:?err}:8081/auth/

networks:
  app-jee-html5:
