version: "2"

services:
  web:
    hostname: web
    container_name: kitchensink-web
    image: kitchensink-angular:0.3.0
    networks:
      kitchensink-angular:
        aliases:
          - web
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    environment:
      - JCMS_JBOSS_SERVER_OPTS=--debug 8787

networks:
  kitchensink-angular:



