include::shared-doc/attributes.adoc[]

:toc:
:toclevels: 4
:numbered:

ifndef::ProductRelease,EAPCDRelease[]
= Auth tests based on WildFly Quickstarts

[toc]

[abstract]
The original Wildlfy quickstarts demonstrate Jakarta EE 8 and a few additional technologies from the WildFly stack. They provide small, specific, working examples that can be used as a reference for your own project.

These examples have been repackaged to use the jkube maven plugin to create a docker file and reduces manual steps to get started without installing a local Wildfly. Most of the examples can also be run in Kubernetes.

The focus of the selected quickstarts relates to security and some parts are based on the Keycloak quickstarts. The Kitchensink is a rewrite of the WF quickstart AngularJS UI, using several examples from the Angular `Tour of heroes` tutorial.


[[introduction]]
== Introduction

_Note_: Most text below and in the examples is from the original quick start documentation, https://github.com/wildfly/quickstart.git. The framework and code from some examples are reused.

My testing has been done on a Fedora 32, using Wildfly 20. This includes checking out the tag `20.0.1.Final`, from quickstart. For demo purposes I've also used a clean Wildfly docker image from https://hub.docker.com/r/jboss/wildfly/.

Please consider running `mvn clean package -Pdocs` to render html documentation with complete urls and other information for the quickstarts.

== Plans

1. wildfly quickstart deltaspike-authorization, adds jkube (docker+k8s)
2. deltaspike - ldap-security using an openldap docker container instead of wf accounts
3. deltaspike - openid-security using a keycloak 10.0.0 IdP container + service adapter
4. keycloak quickstart app-profile-saml-jee-jsp - saml-security, IdP/service adapter, adds roles
5. wildfly quickstart kitchensink-angular - originally using AngularJS, adds Angular 10 UI
6. keycloak quickstart app-jee-html5 - openid-security for a REST API and a separate html5 app, adds jkube (docker+k8s)
7. app-jee-html5-prometheus - REST API, adding microprofile metrics + Prometheus/Grafana
8. TBD: what's next?

[[available_quickstarts]]
== Table of Available Quickstarts

All available quickstarts, which are listed in the following table, can be found here: {githubRepoUrl}.

Each quickstart provides the list of technologies demonstrated by the quickstart and the required experience level needed to build and deploy it. Click on the quickstart link in the table to see more detailed information about how to run it. Some quickstarts require deployment of other quickstarts. This information is noted in the `Prerequisites` section of the quickstart `README.html` file.

NOTE: Some of these quickstarts use the H2 database included with WildFly. It is a lightweight, relational example datasource that is used for examples only. It is not robust or scalable, is not supported, and should NOT be used in a production environment!

NOTE: Some of these depends on each other and the setup inclues a local repo for its own artifacts. Due to have Maven dependencies work you may have to first deploy the main module, for example with the command:
[source,subs="attributes+",options="nowrap"]
----
$ mvn -pl . deploy
----


//<TOC>
[cols="1,1,2,1,1", options="header"]
|===
| Quickstart Name | Demonstrated Technologies | Description | Experience Level Required | Prerequisites 
| link:app-jee-html5/README{outfilesuffix}[app-jee-html5]|html5, WildFly Elytron, Keycloak, OpenID | Demonstrate how to configure Wildlfy Elytron with a keycloak Adapter for openid reusing the login/role UI code from app-jee-html5.  | Unknown | _none_
| link:app-jee-html5-prometheus/README{outfilesuffix}[app-jee-html5-prometheus]|html5, WildFly Elytron, Keycloak, microprofile-metrics, OpenID, Prometheus, Grafana | Demonstrate how to configure Wildlfy Elytron with a keycloak Adapter for openid reusing the login/role UI code from app-jee-html5. Collecting application and wildfly metrics into Prometheus/Grafana. | Unknown | _none_
| link:deltaspike-authorization/README{outfilesuffix}[deltaspike-authorization]|JSF, CDI, Deltaspike, Docker, jkube | Demonstrate the creation of a custom authorization example using @SecurityBindingType from DeltaSpike. This is an updated version of the Wildfly quickstart which uses the jkube maven plugin to create a docker file and reduces manual steps to get started without installing a local Wildfly. | Beginner | _none_
| link:kitchensink-angular/README{outfilesuffix}[kitchensink-angular]|AngularJS, Angular 10, CDI, JPA, EJB, JPA, JAX-RS, BV | The `kitchensink-angular` quickstart demonstrates a {javaVersion} application using Angular JS/10 with JAX-RS, CDI, EJB, JPA, and Bean Validation. This is a modification using an Angular 10 UI. It is also updated to use the jkube maven plugin to create a docker file and reduce manual steps to get started without installing a local Wildfly. | Intermediate | _none_
| link:ldap-security/README{outfilesuffix}[ldap-security]|JSF, CDI, Deltaspike, WildFly Elytron, LDAP | Demonstrate how to configure Wildlfy Elytron for LDAP reusing the login/role UI code from Quickstart deltaspike-authorization. | Unknown | _none_
| link:openid-security/README{outfilesuffix}[openid-security]|JSF, CDI, Deltaspike, WildFly Elytron, Keycloak, OpenID | Demonstrate how to configure Wildlfy Elytron with a keycloak Adapter for openid reusing the login/role UI code from Quickstart deltaspike-authorization.  | Unknown | _none_
| link:saml-security/README{outfilesuffix}[saml-security]|JSP, WildFly Elytron, Keycloak, SAML | Demonstrate how to configure Wildlfy Elytron with a keycloak Adapter for saml reusing the login/role UI code from the keycloak Quickstart app-profile-saml-jee-jsp. Adds role info to UI and role mappers. | Unknown | _none_
|===
//</TOC>

