include::shared-doc/attributes.adoc[]

:toc:
:toclevels: 4
:numbered:

ifndef::ProductRelease,EAPCDRelease[]
= Auth tests based on WildFly Quickstarts

[toc]

[abstract]
The quickstarts demonstrate Jakarta EE 8 and a few additional technologies from the WildFly stack. They provide small, specific, working examples that can be used as a reference for your own project.

[[introduction]]
== Introduction

_Note_: Most text below and in the examples is from the original quick start documentation, https://github.com/wildfly/quickstart.git. The framework and code from some examples are reused.

My testing has been done on a Fedora 32, using Wildfly 19. This includes checking out the tag `19.0.0.Final`, from quickstart. For demo purposes I've also used a clean Wildfly docker image from https://hub.docker.com/r/jboss/wildfly/.

Please consider running `mvn clean package -Pdocs` to render html documentation with complete urls and other information for the quickstarts.

== Plans

1. copied from quickstart - deltaspike-authorization
2. done - ldap-security using an openldap docker container
3. openid-security using a keycloak 10.0.0 IdP container + service adapter
4. saml-security using a keycloak 10.0.0 IdP container + service adapter
5. Other UI than JSF...

// The following is included for all versions: WildFly, JBoss EAP, and EAP CD
[[available_quickstarts]]
== Table of Available Quickstarts

All available quickstarts, which are listed in the following table, can be found here: {githubRepoUrl}.

Each quickstart provides the list of technologies demonstrated by the quickstart and the required experience level needed to build and deploy it. Click on the quickstart link in the table to see more detailed information about how to run it. Some quickstarts require deployment of other quickstarts. This information is noted in the `Prerequisites` section of the quickstart `README.html` file.

NOTE: Some of these quickstarts use the H2 database included with WildFly. It is a lightweight, relational example datasource that is used for examples only. It is not robust or scalable, is not supported, and should NOT be used in a production environment!

//<TOC>
[cols="1,1,2,1,1", options="header"]
|===
| Quickstart Name | Demonstrated Technologies | Description | Experience Level Required | Prerequisites 
| link:deltaspike-authorization/README{outfilesuffix}[deltaspike-authorization]|JSF, CDI, Deltaspike | Demonstrate the creation of a custom authorization example using @SecurityBindingType from DeltaSpike | Beginner | _none_
| link:ldap-security/README{outfilesuffix}[ldap-security]|JSF, CDI, Deltaspike, WildFly Elytron, LDAP | Demonstrate how to configure Wildlfy Elytron for LDAP reusing the login/role UI code from Quickstart deltaspike-authorization. | Unknown | _none_
| link:openid-security/README{outfilesuffix}[openid-security]|JSF, CDI, Deltaspike, WildFly Elytron, Keycloak, OpenID | Demonstrate how to configure Wildlfy Elytron with a keycloak Adapter for openid reusing the login/role UI code from Quickstart deltaspike-authorization.  | Unknown | _none_
|===
//</TOC>

