version: "2"

services:
  ldap:
    hostname: ldap
    image: ldap-security-openldap:0.3.0
    networks:
      openid-security:
        aliases:
          - ldap
    ports:
      - "389:389"
    environment:
      - LDAP_ORGANISATION=wildfly
      - LDAP_DOMAIN=wildfly.org
      - LDAP_ADMIN_PASSWORD=admin

  idp:
    hostname: idp
    image: openid-security-keycloak:0.3.0
    networks:
      openid-security:
        aliases:
          - idp
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm_data.json
    volumes:
      - /tmp/realm_data.json:/tmp/realm_data.json

  web:
    hostname: web
    image: openid-security-wildfly:0.3.0
    networks:
      openid-security:
        aliases:
          - web
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    environment:
      - JCMS_JBOSS_SERVER_OPTS=--debug 8787
    environment:
      - LDAP_URL=ldap://192.168.1.155:389
      - LDAP_ADMIN_PASSWORD=admin


networks:
  openid-security:
