version: "3"

services:
  ldap:
    hostname: ldap
    image: auth-test/ldap-security-openldap:0.4.0
    networks:
      openid-security:
        aliases:
          - ldap
    ports:
      - "389:389"
    environment:
      - LDAP_ORGANISATION=wildfly
      - LDAP_DOMAIN=wildfly.org
      - LDAP_ADMIN_PASSWORD=admin

  idp:
    hostname: idp
    image: auth-test/openid-security-keycloak:0.4.0
    networks:
      openid-security:
        aliases:
          - idp
    ports:
      - "8081:8080"
    environment:
      - WEB_URL=http://${THIS_HOST:?err}:8080/openid-security-wildfly
      - LDAP_URL=ldap://${THIS_HOST:?err}:389
      # todo: - LDAP_ADMIN_PASSWORD=admin
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin

  web:
    hostname: web
    image: auth-test/openid-security-wildfly:0.4.0
    networks:
      openid-security:
        aliases:
          - web
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    environment:
      - JCMS_JBOSS_SERVER_OPTS=--debug 8787
      - IDP_URL=http://${THIS_HOST:?err}:8081/auth/

networks:
  openid-security:
