include::../shared-doc/attributes.adoc[]

= openid-security: reuses deltaspike-authorization for openid authentication
:author: Tomas Aronsson
:level: Unknown
:technologies: JSF, CDI, Deltaspike, WildFly Elytron, Keycloak, OpenID

[abstract]
Demonstrate how to configure Wildlfy Elytron with a keycloak Adapter for openid reusing the login/role UI code from Quickstart deltaspike-authorization. 

== What is it?

Based on the keycloak docs:

* https://www.keycloak.org/docs/latest/securing_apps/#jboss-eap-wildfly-adapter

Requires:

 * Wildfly > 11, tested on Wildfly 19
 * A configured LDAP (see ldap-security example)
 * A manually installed keycloak adapter for Wildfly
 * A configured IdP server, see below

== Configure an IdP server

For the sake of simplicity, we will start a Containerised version of Keycloak, quay.io/keycloak/keycloak:10.0.x

[source,subs="+quotes,attributes+",options="nowrap"]
----
# Use a prepackaged keycloak
IMAGE=quay.io/keycloak/keycloak:10.0.0

# Import predefined realm. Do not detach, log is useful for troubleshooting
docker run --rm -p 8080:8080 --name keycloak_idp -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin -e  KEYCLOAK_IMPORT=/tmp/realm_data.json -v $(pwd)/idp_realm_auth_test.json:/tmp/realm_data.json $IMAGE
----

A realm can be configured manually and then exported using commands like:

[source,subs="+quotes,attributes+",options="nowrap"]
----
# Start an empty Idp, mount an export dir
mkdir tmp
docker run --rm -d -p 8180:8080 --name kc_tmp -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin -v $(pwd)/tmp:/tmp $IMAGE

# Manually define a new realm called auth_test and export it from the docker
docker exec -it kc_tmp /opt/jboss/keycloak/bin/standalone.sh -Djboss.socket.binding.port-offset=100 -Dkeycloak.migration.action=export -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.usersExportStrategy=REALM_FILE -Dkeycloak.migration.realmName=auth_test -Dkeycloak.migration.file=/tmp/export_realm.json
----

[[configure_the_server]]
== Configure the Server

The openid war file does not need any special JBoss CLI commands except for installing a Keycloak adapter, example from Dockerfile:

[source,subs="+quotes,attributes+",options="nowrap"]
----
# Install keycloak adapter
COPY keycloak-wildfly-adapter-dist-10.0.1.tar.gz /tmp/
RUN cd /opt/jboss/wildfly && tar zxf /tmp/keycloak-wildfly-adapter-dist-10.0.1.tar.gz &&  ./bin/jboss-cli.sh --file=bin/adapter-elytron-install-offline.cli
----

== Access the application

The application will be running at the following URL: http://<external ip>:8080/{artifactId}/.

*Note*: With the IdP and the Wildfly running inside NAT:ed containers they cannot use localhost as the hostname. Both the IdP and Wildfly launch scripts takes environment variables like $IDP_HOST, $WEB_HOST. For openid to work they seems to have to be the same in all places, including the url you type in the browser to access the application.

When you access the application you are redirected to a Keycloak login form. Once you have logged into the application you see a page showing your username and two buttons.

When you click on the `User Method` button you will see the following message: `You executed a @UserAllowed method` - you are authorized to invoke this method.

When you click on the `Admin Method` button, you are redirected to an error page with the following exception: `org.apache.deltaspike.security.api.authorization.AccessDeniedException` because you aren't authorized to invoke this method.
