include::../shared-doc/attributes.adoc[]

= openid-security: reuses deltaspike-authorization for openid authentication
:author: Tomas Aronsson
:level: Unknown
:technologies: JSF, CDI, Deltaspike, WildFly Elytron, Keycloak, OpenID

[abstract]
Demonstrate how to configure Wildlfy Elytron with a keycloak Adapter for openid reusing the login/role UI code from Quickstart deltaspike-authorization. 

== What is it?

Based on the keycloak docs:

* https://www.keycloak.org/docs/latest/securing_apps/#jboss-eap-wildfly-adapter

Included components:

 * Wildfly > 11, tested on Wildfly 20
 * A configured LDAP (see ldap-security example)
 * An installed keycloak adapter for Wildfly
 * A configured IdP server, see below

// System Requirements
include::../shared-doc/system-requirements.adoc[leveloffset=+1]

[[configure_the_idp]]
== Configure the Identity provider (IdP)

The IdP is based on Keycloak, quay.io/keycloak/keycloak:10.0.x. This image can take a json file as input to setup the configuration, in this case to find an ldap server and accept the wildfly app as a recognized service to authenticate.

This is federated authentication where the browser communicates with the Idp and the service. Both these must be available as externel interfaces, it is not enough to only use docker or kubernetes networks.

When running with docker-compose, there is a wrapper script that updates the Idp config to use ports on the host where docker-compose is started:

[source,subs="+quotes,attributes+",options="nowrap"]
----
idp/src/main/resources/idp_setup.sh
----

A realm can be configured manually and then exported using commands like:

[source,subs="+quotes,attributes+",options="nowrap"]
----
# Start an empty Idp, mount an export dir
mkdir tmp
docker run --rm -d -p 8180:8080 --name kc_tmp -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin -v $(pwd)/tmp:/tmp $IMAGE

# Manually define a new realm called auth_test and export it from the docker
docker exec -it kc_tmp /opt/jboss/keycloak/bin/standalone.sh -Djboss.socket.binding.port-offset=100 -Dkeycloak.migration.action=export -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.usersExportStrategy=REALM_FILE -Dkeycloak.migration.realmName=auth_test -Dkeycloak.migration.file=/tmp/export_realm.json
----

// Build and Deploy the Quickstart for Docker
include::../shared-doc/build-and-deploy-the-quickstart-docker.adoc[leveloffset=+1]

// Build and Deploy the Quickstart for Kubernetes
include::../shared-doc/build-and-deploy-the-quickstart-kubernetes.adoc[leveloffset=+1]

[[configure_the_wildfly]]
== Configure the Wildfly manually

The openid war file does not need any special JBoss CLI commands except for installing a Keycloak adapter, example from Dockerfile:

[source,subs="+quotes,attributes+",options="nowrap"]
----
# Install keycloak adapter
COPY keycloak-wildfly-adapter-dist-10.0.1.tar.gz /tmp/
RUN cd /opt/jboss/wildfly && tar zxf /tmp/keycloak-wildfly-adapter-dist-10.0.1.tar.gz &&  ./bin/jboss-cli.sh --file=bin/adapter-elytron-install-offline.cli
----

== Access the application

The application will be running at the following URL: http://<external ip>:8080/{artifactId}/.

*Note*: With the IdP and the Wildfly running inside NAT:ed containers they cannot use localhost as the hostname. Both the IdP and Wildfly launch scripts takes environment variables like $IDP_HOST, $WEB_HOST. For openid to work they seems to have to be the same in all places, including the url you type in the browser to access the application.

When you access the application you are redirected to a Keycloak login form. Once you have logged into the application you see the deltaspike app welcome page.
