version: "2"

services:
  ldap:
    hostname: ldap
    image: auth-test/ldap-security-openldap:0.4.0
    networks:
      ldap-security:
        aliases:
          - ldap
    ports:
      - "389:389"
    environment:
      - LDAP_ORGANISATION=wildfly
      - LDAP_DOMAIN=wildfly.org
      - LDAP_ADMIN_PASSWORD=admin

  web:
    hostname: web
    image: auth-test/ldap-security-wildfly:0.4.0
    networks:
      ldap-security:
        aliases:
          - web
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    environment:
      - JCMS_JBOSS_SERVER_OPTS=--debug 8787
    environment:
      - LDAP_URL=ldap://192.168.1.155:389
      - LDAP_ADMIN_PASSWORD=admin


networks:
  ldap-security:



