include::../shared-doc/attributes.adoc[]

= ldap-security: reuses deltaspike-authorization for ldap authentication. Demonstrate the creation of a custom authorization example using @SecurityBindingType from DeltaSpike
:author: Tomas Aronsson
:level: Unknown
:technologies: JSF, CDI, Deltaspike, WildFly Elytron, LDAP

[abstract]
Demonstrate how to configure Wildlfy Elytron for LDAP reusing the login/role UI code from Quickstart deltaspike-authorization.

== What is it?

Based on http://www.mastertheboss.com/jboss-server/jboss-security/configuring-ldap-based-authentication-with-elytron-on-wildfly, included components:

 * Wildfly > 11, tested on Wildfly 20
 * An LDAP Server or a Docker deamon to start an LDAP Server in a Container
 * opendap-clients: ldapadd and ldapsearch

// Build and Deploy the Quickstart for Docker
include::../shared-doc/build-and-deploy-the-quickstart-docker.adoc[leveloffset=+1]
// Build and Deploy the Quickstart for Kubernetes
include::../shared-doc/build-and-deploy-the-quickstart-kubernetes.adoc[leveloffset=+1]

[[configure_the_ldap]]
== Manually configure the LDAP server

The ldap is based on openldap, using the container osixia/openldap. See 

[source,subs="+quotes,attributes+",options="nowrap"]
----
ldap/src/main/resources/ldap_setup.sh
----
For an example of launching it manually, import am ldif file and verify that it has been loaded into the ldap.

[[configure_the_wildfly]]
== Configure the Wildfly manually

You configure the security domain by running JBoss CLI commands. For your convenience, this quickstart batches the commands into a `configure-elytron.cli` script provided in the directory `web/src/main/cli` in this quickstart.

. Before you begin, make sure you do the following:

* xref:back_up_standalone_server_configuration[Back up the {productName} standalone server configuration] as described above.
* xref:start_the_eap_standalone_server[Start the {productName} server with the standalone default profile] as described above.

. Review the `configure-elytron.cli` file in the root of this quickstart directory. This script adds the configuration that enables Elytron security for the quickstart components. Comments in the script describe the purpose of each block of commands.
. Open a new terminal, navigate to the root directory of this quickstart, and run the following command, replacing `__{jbossHomeName}__` with the path to your server:
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/jboss-cli.sh --connect --file=configure-elytron.cli
----

You should see the following result when you run the script:
+
[source,options="nowrap"]
----
The batch executed successfully
process-state: reload-required
----

// System Requirements
include::../shared-doc/system-requirements.adoc[leveloffset=+1]
// Use of {jbossHomeName}
include::../shared-doc/use-of-jboss-home-name.adoc[leveloffset=+1]
// Add the Authorized Application and Management Users
// include::../shared-doc/add-application-user.adoc[leveloffset=+1]
// Start the Server
include::../shared-doc/start-the-standalone-server.adoc[leveloffset=+1]
// Build and Deploy the Quickstart
include::../shared-doc/build-and-deploy-the-quickstart.adoc[leveloffset=+1]


== Access the application

The application will be running at the following URL: http://localhost:8080/{artifactId}-wildfly/. It looks just like the deltaspike app, but uses ldap for the authentication.
