version: "2"

services:
  web:
    hostname: web
    container_name: deltaspike-web
    image: auth-test/deltaspike-authorization:0.4.0
    networks:
      deltaspike-authorization:
        aliases:
          - web
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    environment:
      - JCMS_JBOSS_SERVER_OPTS=--debug 8787

networks:
  deltaspike-authorization:



