apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-settings
data:
  # property-like keys; each key maps to a simple value
  ldap.domain: "wildfly.org"
  ldap.admin.password: "admin"
  # The service inside k8s
  ldap.service.url: "ldap://ldap-service.default.svc.cluster.local:389"
  # sample data, not yet used
  ldap_properties_file_name: "ldap.properties"

  # file-like keys
  ldap.properties: |
    userdir.src = ldif
    userdir.type = openldap
