[[add_the_application_user]]
= Add the Authorized Application User

// Note: The group ID syntax must be defined in the calling topic.
// using the document attribute :app-user-groups:
// Use a comma-delimited list to define more than one group.
//
// :app-user-groups: guest, users

ifdef::app-user-groups[]
:app-group-list: {app-user-groups}
:app-group-command: -g '{app-user-groups}'
endif::app-user-groups[]

ifndef::app-user-groups[]
:app-group-list:
:app-group-command:
endif::app-user-groups[]

This quickstart uses secured management interfaces and requires that you create the following application user to access the running application.

[cols="20%,20%,20%,40%",options="headers"]
|===
|UserName |Realm |Password |Roles

|guest |ApplicationRealm |abcd123 |{app-group-list}
|appuser |ApplicationRealm |abcd123 |{app-group-list}
|appadmin |ApplicationRealm |abcd123 |{app-group-list}
|developer |ApplicationRealm |abcd123 |{app-group-list}
|===

The users and their groups can be added to the Wildlfy image by updating the pom.xml file to run add-user.sh when the image is built:
[source,subs="+quotes,attributes+",options="nowrap"]
----
	<configuration>
	  <images>
	    <image>
	      <build>
		<runCmds>
		  <run>${jboss_home}/bin/add-user.sh -a -u 'appuser' -p 'abcd123' -g 'appuser'</run>
		</runCmds>
	      </build>
	    </image>
	  </images>
	</configuration>
----


To add the application user, open a terminal, connect to the container and use th add-suser.sh (works in a running Wildfly):
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ docker exec -ti deltaspike-web bash
$jboss@web $JBOSS_HOME/bin/add-user.sh -a -u 'admin' -p 'abcd123' -g 'admin' {app-group-command}
----
