spec:
  replicas: 1
  template:
    spec:
      containers:
        - env:
          - name: WEB_URL
            value: http://${this.host}:31280/app-html5-prometheus
          - name: IDP_URL
            valueFrom:
              configMapKeyRef:
                name: idp-settings
                key: idp.service.url
