{
 "title": "Application metrics",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "application_org_keycloak_quickstart_jaxrs_Resource_performedAdmin_total"
    },
    {
     "expr": "application_org_keycloak_quickstart_jaxrs_Resource_performedPublic_total"
    },
    {
     "expr": "application_org_keycloak_quickstart_jaxrs_Resource_performedSecured_total"
    }
   ]
  },
  {
   "title": "Wildfly - undertow statistics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wildfly_undertow_bytes_received_total_bytes"
    },
    {
     "expr": "wildfly_undertow_bytes_sent_total_bytes"
    },
    {
     "expr": "wildfly_undertow_rejected_sessions_total"
    }
   ]
  },
  {
   "title": "Total number of requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_org_keycloak_quickstart_jaxrs_Resource_performedAdmin_total"
    },
    {
     "expr": "application_org_keycloak_quickstart_jaxrs_Resource_performedPublic_total"
    },
    {
     "expr": "application_org_keycloak_quickstart_jaxrs_Resource_performedSecured_total"
    }
   ]
  },
  {
   "title": "Frequency per 15m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_adminTimer_fifteen_min_rate_per_second"
    },
    {
     "expr": "application_publicFrequency_fifteen_min_rate_per_second"
    },
    {
     "expr": "application_securedFrequency_fifteen_min_rate_per_second"
    }
   ]
  },
  {
   "title": "Average response times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_adminTimer_mean_seconds"
    },
    {
     "expr": "application_publicTimer_mean_seconds"
    },
    {
     "expr": "application_securedTimer_mean_seconds"
    }
   ]
  }
 ]
}