{
 "title": "Wildfly",
 "description": "Dashboard for monitoring JBoss EAP",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job:",
    "query": "label_values(wildfly_jgroups_num_threads, job)"
   },
   {
    "name": "instance",
    "label": "Instance:",
    "query": "label_values(wildfly_jgroups_num_threads{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Heap Usage",
   "type": "graph",
   "description": "Heap usage per JVM. Max heap is defined by environment.yml settings.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(instance,job) (base:memory_used_heap_bytes{instance=~\"${instance:pipe}:.*\",job=~\"$job\"})",
     "legendFormat": "{{job}}: {{instance}}"
    }
   ]
  },
  {
   "title": "Heap Usage Percent",
   "type": "graph",
   "description": "Percentage of max heap usage per JVM. Max heap is defined by environment.yml settings.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by(job,instance) (100 * base:memory_used_heap_bytes{instance=~\"${instance:pipe}:.*\",job=~\"$job\"} / base:memory_max_heap_bytes{instance=~\"${instance:pipe}:.*\",job=~\"$job\"})",
     "legendFormat": "{{job}}: {{instance}}"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "graph",
   "description": "Current threads in the JVM.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance,job) (wildfly_jgroups_num_threads{instance=~\"${instance:pipe}:.*\",job=~\"$job\"})",
     "legendFormat": "{{job}}: {{instance}}"
    }
   ]
  },
  {
   "title": " I/O Threads",
   "type": "graph",
   "description": "Threads in the Wildlfy I/O pool. Todo: Wildfly has several thread pools that might be relevant to consider.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wildfly_io_io_thread_count{instance=~\"${instance:pipe}:.*\",job=~\"$job\"}",
     "legendFormat": "{{job}}: {{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory, non heap",
   "type": "graph",
   "description": "Most JVM memory is on the heap, but it also allocates some additonal memory.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "base:memory_used_non_heap_bytes{job=~\"$job\",instance=~\"${instance:pipe}:.*\"}",
     "legendFormat": "{{job}}: {{instance}}"
    }
   ]
  }
 ]
}