spec:
  replicas: 1
  template:
    spec:
      containers:
        - env:
          - name: LDAP_URL
            valueFrom:
              configMapKeyRef:
                name: ldap-settings
                key: ldap.service.url
          - name: LDAP_ADMIN_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: ldap-settings
                key: ldap.admin.password
